### ISSUE TITLE
addEdges(List<Edge> edges, boolean checkVertex)中checkVertex不同设置有啥区别？

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph-client#102]
addEdges(List<Edge> edges, boolean checkVertex)
boolean checkVertex 设置为true/false有什么区别吗？

我测试了下，批量导入边时
1条边是正常的，
另外1条边，目标顶点是不存在的。

调用这个接口，不管checkVertex 设置为true/false，正常的边都可以导入，缺失顶点的边都没能导入。

求解答？

**Comment by Linary** [comment]
@tmljob 
- checkVertex 设置为true时会检查边的源顶点和目标顶点是否存在，如果不存在，则边添加不进去；
- checkVertex 设置为false时不做检查，边都能添加进去。

你说的“不管checkVertex 设置为true/false，正常的边都可以导入，缺失顶点的边都没能导入”，应该是在checkVertex为false时，边进去了，但是因为它悬空了，没能查出来。你用g.E().count()对比下这两种情况下边的数目。

**Comment by tmljob** [comment]
> @tmljob
> 
> * checkVertex 设置为true时会检查边的源顶点和目标顶点是否存在，如果不存在，则边添加不进去；
> * checkVertex 设置为false时不做检查，边都能添加进去。
> 
> 你说的“不管checkVertex 设置为true/false，正常的边都可以导入，缺失顶点的边都没能导入”，应该是在checkVertex为false时，边进去了，但是因为它悬空了，没能查出来。你用g.E().count()对比下这两种情况下边的数目。

基于上述描述，“checkVertex 设置为false时不做检查，边都能添加进去” /“在checkVertex为false时，边进去了，但是因为它悬空了，没能查出来”
1、那后面这个悬空边对应的顶点入库了，是否就正常了？
2、是否可以用这种方式，解决边和顶点入库不能同步的问题，设置为false，边先进去，顶点可以再补上。

**Comment by tmljob** [comment]
感谢解答，经过验证，确如所说：

> checkVertex 设置为true时会检查边的源顶点和目标顶点是否存在，如果不存在，则边添加不进去；
     **addEdges 接口设置为true时，只要批次数据里面存在顶点不存在的情况，那这个批次都会添加不进去（抛出异常）**
> checkVertex 设置为false时不做检查，边都能添加进去。
    **可以用这种方式，解决边和顶点入库不能同步的问题，设置为false，边先进去，顶点可以再补上**

多谢 @Linary
