### ISSUE TITLE
创建属性报错： class java.lang.IllegalArgumentException: The name of property key can't be null

### ISSUE THREAD

**Issue by 472732787** [hugegraph/hugegraph-client#104]
创建属性报错   ![image](https://user-images.githubusercontent.com/6340234/96201948-7d7d4100-0f90-11eb-9bd8-d6edb877f357.png)

**Comment by 472732787** [comment]
大佬，请问这个是什么原因造成的

**Comment by 472732787** [comment]
会和其他 jar依赖的  guava  fasterxml 。。。冲突，集成到项目里没法用，只能单独搞一个项目

**Comment by javeme** [comment]
@472732787 可以参考 https://github.com/hugegraph/hugegraph/issues/5

**Comment by 472732787** [comment]
@javeme  该文档 提供了思路 ，很有用 ，按照这个修改后依然存在问题， 我的项目中 去掉 jackson-databind   加入 jackson-annotations （2.10.2） 问题解决
