### ISSUE TITLE
关于huge client能否有个说明文档，比如用户，用户组，资源，权限等方面的文档，一直不敢确定它们之间的关系，以及是否正确的使用。缺乏文档指导

### ISSUE THREAD

**Issue by dyhyao6** [hugegraph/hugegraph-client#105]
@Linary @javeme ，thanks!

**Comment by dyhyao6** [comment]
@javeme @Linary 请问有这方面的文档吗？

**Comment by imbajin** [comment]
auth 相关的问题可以参考 [rest-api-auth](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/auth.html), client 的确没有单独重新说明, 但是它本质和 rest-api 是一致的.

也欢迎提供相关实践文档, 或提一下具体什么地方不好使用 / 理解
