### ISSUE TITLE
[Feature] java client支持连接多个huge server

### ISSUE THREAD

**Issue by hhhyang** [hugegraph/hugegraph-client#124]
## Feature Description:

当前java client只支持与单个huge server连接，是否可以考虑连接多个huge server？这样可以在多个后端之间做负载均衡

当前创建HugeClient只支持配置单个url：
```
public static HugeClientBuilder builder(String url, String graph) {
        return new HugeClientBuilder(url, graph);
    }
```

**Comment by hhhyang** [comment]
多谢，上面是一个通用的解决方案。

不过如果通过vip或nginx等方式的，需要引入一个基础设施，有些场景不一定那么容易获得。引入vip或nginx增加了访问节点，且需要人维护。如果java client支持客户端负载均衡的话（不需要支持复杂的算法，比如RR，开放一个用户自定义接口即可），我觉得更方便用户部署、应用hugegraph。

**Comment by imbajin** [comment]
如果追求简单, 可选择这几种方案:
1. 单个 server, 启用一下内置的自动拉起 + crontab 组合
2. 多个 server, 但是业务层去对应区分, 比如读写分离, 一个 server 只用来写, 一个用来读.
3. 你调用 HugeClient 的时候, 创建多个, 然后自己简单写个轮询/权重控制

你的场景可以优先考虑 2/3 方案, 大部分场景来说也足矣了 (需要秒级的 HA, client 负载均衡也没法做到)

所以仔细想一下, 在 client 本身内置负载均衡的处理其实是有很多轻量级代替方案的, 如果重一点, 那就不如直接用 nginx, 而且后续我们会提供 nginx 的内置整合方案的, 并不需要单独有人维护 (它本来也不重)

当然多谢您的建议和反馈, 也欢迎多交流提出 idea
