### ISSUE TITLE
关于Traverser中paths的post方法的api

### ISSUE THREAD

**Issue by wxj7king** [hugegraph/hugegraph-client#126]
你好，我是用的是docker版的hugegraph，因为需要获得只有某几种边的所有路径，然后我自己写了这个paths的post方法的api，但是发现请求的时候报错，请问是docker的hugegraph版本太低了吗，还是其他的原因，谢谢！
![image](https://user-images.githubusercontent.com/26570611/122351294-948d8c00-cf80-11eb-8eb6-183db28bc6d1.png)

**Comment by imbajin** [comment]
从你报错来看, 应该是没正确配置好你新增的 api 导致识别不到

理论上跟 docker 本身没啥关系, 版本是否低也取决于你配套的 client / loader 的版本, 只要是配套的就不会有版本问题.

你可以多给一点详细的上下文... 把具体的 client/server 版本, 增加的 API 代码位置以及具体什么时候报错说清晰一些 (截图也可以稍微全一点), 这样可以更高效定位到问题

**Comment by wxj7king** [comment]
![image](https://user-images.githubusercontent.com/26570611/122359094-d79f2d80-cf87-11eb-9128-e705b86230e4.png)
这是我用python写的，分别是post方法的url和data部分的json

**Comment by wxj7king** [comment]
这是用python写的api
![image](https://user-images.githubusercontent.com/26570611/122489934-5a20ff00-d013-11eb-9c98-81bc58370b25.png)

**Comment by imbajin** [comment]
你先用直接发送请求的 REST-api 工具发送 POST 试试 (like postman or [talend](https://www.talend.com/))

然后再尝试用其他的封装去发送, 对比就能容易发现原因了, 一步步缩小问题范围. 405一般说明发送方式不符合, 比如 get 方法发送了 post 请求.

**Comment by wxj7king** [comment]
好的，我去试试！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月18日(周五) 中午1:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hugegraph/hugegraph-client] 关于Traverser中paths的post方法的api (#126)




 
你先用直接发送请求的 REST-api 工具发送 POST 试试 (like postman or talend)
 
然后再尝试用其他的封装去发送, 对比就能容易发现原因了, 一步步缩小问题范围. 405一般说明发送方式不符合, 比如 get 方法发送了 post 请求.

**Comment by wxj7king** [comment]
不好意思回复晚了，我用postman试了一下还是405的问题，我用我自己写的接口，其他使用post方法的api是都能用的0.0
![image](https://user-images.githubusercontent.com/26570611/122850247-7a1c2f80-d33f-11eb-9eea-52fb5d7f15e7.png)

**Comment by imbajin** [comment]
哦是, 因为 paths 的 post 方法是0.11之后正式加入的, docker 里默认是0.10

> "然后我自己写了这个 paths 的 post 方法的 api"

我以为你自己在 server 端加入了**自定义**的 post-paths 的 api, 如果你这只是在 py/client 端包装了一下 那的确是不支持的, 另外你从 `Headers` 的 `Allow` 来看也很好, 这样是一个确认方式

**Comment by wxj7king** [comment]
好的，谢谢你的解答！
