### ISSUE TITLE
hugegraph-client 内置了SLF4J进行日志打印，默认等级为debug，输出的信息较多，如何修改日志等级？

### ISSUE THREAD

**Issue by GZYBigGG** [hugegraph/hugegraph-client#131]
请问如何修改hugegraph-client 的日志等级？自行配置log4j.properties无效。

**Comment by imbajin** [comment]
SLF4J 应该只是一个包装吧, 实际 client (整个 hugegraph 中) 引用的是 `common` 模块里的 `log4j2` 才对.

你可以参考一下 huegraph-loader 的 `log4j2.xml` 配置(包括放置未知), 修改一下默认日志输出级别就可以了.
