### ISSUE TITLE
Vertex中Blob类型的属性赋值问题

### ISSUE THREAD

**Issue by CircleLife** [hugegraph/hugegraph-client#132]
### Expected behavior 期望表现
假设vertex中属性abstract为Blob类型（byte数组），通过vertex.property("abstract", ((String) value).getBytes())进行赋值。期望赋值成功。

### Actual behavior 实际表现
赋值失败，底层校验不通过，提示java.lang.IllegalArgumentException: Invalid property value type: 'class [B'。

GraphElement.property()：
E.checkArgument(ReflectionUtil.isSimpleType(clazz) || clazz.equals(UUID.class) || clazz.equals(Date.class) || value instanceof List || value instanceof Set, "Invalid property value type: '%s'", new Object[]{clazz});

**Comment by imbajin** [comment]
> This is still a problem in latest version of hugegraph client. byte[] is still not allowed in checkArgument. I'm using graph().addVertices(...), so cannot use the addVertex() workaround mentioned above.
> 
> ```java
>     public GraphElement property(String name, Object value) {
>         E.checkArgumentNotNull(name, "property name");
>         E.checkArgumentNotNull(value, "property value");
> 
>         Class<?> clazz = value.getClass();
>         E.checkArgument(ReflectionUtil.isSimpleType(clazz) ||
>                         clazz.equals(UUID.class) ||
>                         clazz.equals(Date.class) ||
>                         value instanceof List ||
>                         value instanceof Set,
>                         "Invalid property value type: '%s'", clazz);
> 
>         this.properties.put(name, value);
>         return this;
>     }
> ```

thanks for feedback, could u use the master branch to build a huge-client then test if it's OK?

and what's your version of client now?

**Comment by metametametameta** [comment]
Hi,

I was on hugegraph client version 1.9.4 earlier. I did a brand new build from master today (https://github.com/hugegraph/hugegraph-client) (now version 1.9.5), but still same issue.

Thanks,

**Comment by imbajin** [comment]
OK, assign test-dev to ensure it and will be fixed later(if exists)
