### ISSUE TITLE
How to delete all data?

### ISSUE THREAD

**Issue by yuyang0** [hugegraph/hugegraph-client#4]
I know `graphs().clear`, but the number of data is more than 10000, any advices?

**Comment by javeme** [comment]
Currently we have 3 ways to clear all the data:
1.clear backend store and init backend again
2.clear by Gremlin with batch commit:
```java
count = 0
all = g.V()
while(all.hasNext()) {
    all.next().remove()
    if (++count > 500) {
        g.tx().commit()
        count = 0
    }
}
```
3.query by page and delete one by one
Like:
```shell
# fetch all vertices page by page
GET http://localhost:8080/graphs/hugegraph/graph/vertices?page&limit=20
# delete all vertices one by one
DELETE http://localhost:8080/graphs/hugegraph/graph/vertices/{id}
```
For more details: https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html

**Comment by xffighting** [comment]
Error!
Cannot set readonly property: all for class: org.apache.tinkerpop.gremlin.process.traversal.Pop

> Currently we have 3 ways to clear all the data:
> 
> 1. clear backend store and init backend again
> 2. clear by Gremlin with batch commit:
> 
> ```java
> count = 0
> all = g.V()
> while(all.hasNext()) {
>     all.next().remove()
>     if (++count > 500) {
>         g.tx().commit()
>         count = 0
>     }
> }
> g.tx().commit()
> ```
> 
> 1. query by page and delete one by one
> 
> ```shell
> # fetch all vertices page by page
> GET http://localhost:8080/graphs/hugegraph/graph/vertices?page&limit=20
> # delete all vertices one by one
> DELETE http://localhost:8080/graphs/hugegraph/graph/vertices/{id}
> ```
> 
> For more details: https://hugegraph.github.io/hugegraph-doc/clients/restful-api/vertex.html

When I use the second way, it gives me error:
Error!
Cannot set readonly property: all for class: org.apache.tinkerpop.gremlin.process.traversal.Pop

**Comment by javeme** [comment]
@xffighting Sorry, `all` is a built-in object of gremlin, so we need to add def before it like this:
`def all = g.V()`

**Comment by suesunss** [comment]
@javeme 

hi, I am using: 

```java
count = 0
def all = g.V().has('partition', 'value')
while(all.hasNext()) {
    all.next().remove()
    if (++count > 500) {
        g.tx().commit()
        count = 0
    }
}
g.tx().commit()
```
to delete data having a certain `value` for `partition` property, however, when `all` contains more than 10000 records, an error throws:

```
Vertices size has reached tx capacity 10000
```

As far as I am concerned, in each transaction we only have no more than 500 records, does I misunderstand ? (It seems to me that the transaction has taken all records in `all` into consideration instead of those in the iteration)

I tried fetching only 10000 records in each iterations and loop overs each `VERTEX_TX_CAPACITY`, but this seems a little bit slow.

```java
count = 0
def all = g.V().has('partition', 'value')
while(all.hasNext()){
    while(all.hasNext()) {
        all.next().remove()
        if (++count > 500) {
            g.tx().commit()
            count = 0
        }
    }
    g.tx().commit()
    all = g.V().has('partition', 'value')
}
all.hasNext()
```

Is there a better way to do this ?

**Comment by javeme** [comment]
@suesunss Does the deleted vertices have a large number of edges, since the associated edges are also deleted when deleting vertices, if so we need to delete the associated edges first.

Seems a bit complicated, maybe we should improve and add easy-to-use delete API.

**Comment by suesunss** [comment]
@javeme 

Thanks for the response. Actually I am deleting the edges instead of vertices (sorry for a misleading example).

code like this:

```
count = 0
def all = g.E().has('partition', 'value').limit(10000)
while(all.hasNext()){
    while(all.hasNext()) {
        all.next().remove()
        if (++count > 500) {
            g.tx().commit()
            count = 0
        }
    }
    g.tx().commit()
    all = g.E().has('partition', 'value').limit(10000)
}
all.hasNext()
```

this leads to a similar exception: 

```
Edges size has reached tx capacity 10000
```

**Comment by Linary** [comment]
@suesunss 
Thanks for your comment. Sorry I haven't found a way to reproduce it temporarily, what hugegraph version are you using, and the backend type.

**Comment by suesunss** [comment]
@Linary 

We are using HugeGraph verison 0.10.4, with a RocksDB backend.
