### ISSUE TITLE
hugegraph client can't run with 0.10.0 server

### ISSUE THREAD

**Issue by wangyuxue** [hugegraph/hugegraph-client#51]
running sample program with client 1.7, throw exception:
Exception in thread "main" java.lang.IllegalStateException: The version 0.39.0.0 of 'hugegraph-api in server' is not in [0.38, 0.39)

remove code in HugeClient can reslove it。 

//        VersionUtil.Version apiVersion = VersionUtil.Version.of(
//                                         this.version.getApiVersion());
//        VersionUtil.check(apiVersion, "0.38", "0.39",
//                          "hugegraph-api in server")；

Is VersionUtil check necessary？

**Comment by javeme** [comment]
@wangyuxue hugegraph new version v0.10.0 has not been released yet, so it is not compatible. We are developing and will keep compatible after completion.

> Is VersionUtil check necessary？

yes version check is necessary

**Comment by zhoney** [comment]
hugegraph v0.10.4 has been released along with hugegraph-client 1.8.0. Using matched version client with HugeGraphServer is strongly advised. 

I will close this issue due to solved and no comments for a long time.
