### ISSUE TITLE
The name of property key can't be null

### ISSUE THREAD

**Issue by 0xqq** [hugegraph/hugegraph-client#58]
HugeClient hugeClient = new HugeClient("http://localhost:8080", "hugegraph");
SchemaManager schema = hugeClient.schema();
schema.propertyKey("name").asText().ifNotExist().create();
Caused by: class java.lang.IllegalArgumentException: The name of property key can't be null

**Comment by Linary** [comment]
@0xqq 请放置于一个单独的项目进行测试，这个问题可能是因为hugegraph-client的依赖与其他jackson的包冲突所致。
