### ISSUE TITLE
批量更新边或者顶点的api如何使用？

### ISSUE THREAD

**Issue by wslovenide** [hugegraph/hugegraph-client#61]
看到hugeclient里面有批量更新的接口，但是没有注释，参数不知道该传什么

`public class BatchVertexRequest {

    @JsonProperty("vertices")
    private List<Vertex> vertices;
    @JsonProperty("update_strategies")
    private Map<String, UpdateStrategy> updateStrategies;
    @JsonProperty("create_if_not_exist")
    private boolean createIfNotExist;

    public BatchVertexRequest() {
        this.vertices = null;
        this.updateStrategies = null;
        this.createIfNotExist = true;
    }

    @Override
    public String toString() {
        return String.format("BatchVertexRequest{vertices=%s," +
                             "updateStrategies=%s,createIfNotExist=%s}",
                             this.vertices, this.updateStrategies,
                             this.createIfNotExist);
    }

    public static class Builder {

        private BatchVertexRequest req;

        public Builder() {
            this.req = new BatchVertexRequest();
        }

        public Builder vertices(List<Vertex> vertices) {
            this.req.vertices = vertices;
            return this;
        }

        public Builder updatingStrategies(Map<String, UpdateStrategy> map) {
            this.req.updateStrategies = new HashMap<>(map);
            return this;
        }

        public Builder updatingStrategy(String property,
                                        UpdateStrategy strategy) {
            this.req.updateStrategies.put(property, strategy);
            return this;
        }

        public Builder createIfNotExist(boolean createIfNotExist) {
            this.req.createIfNotExist = createIfNotExist;
            return this;
        }

        public BatchVertexRequest build() {
            E.checkArgumentNotNull(req, "BatchVertexRequest can't be null");
            E.checkArgumentNotNull(req.vertices,
                                   "Parameter 'vertices' can't be null");
            E.checkArgument(req.updateStrategies != null &&
                            !req.updateStrategies.isEmpty(),
                            "Parameter 'update_strategies' can't be empty");
            E.checkArgument(req.createIfNotExist == true,
                            "Parameter 'create_if_not_exist' " +
                            "dose not support false now");
            return this.req;
        }
    }`

updateStrategies必填而且是个map ， 能解释下这个map的key或者value的含义吗，或者该传什么内容？ 我在updateStrategies中随便加了点数据后，执行入下代码：

`            Vertex vertex = new Vertex("user");
            vertex.id("0");
            vertex.property("active_time",System.currentTimeMillis());

            Vertex vertex1 = new Vertex("user");
            vertex1.id("1");
            vertex1.property("active_time",System.currentTimeMillis());

            List<Vertex> list = new ArrayList<>();
            list.add(vertex);
            list.add(vertex1);

            BatchVertexRequest.Builder request = new BatchVertexRequest.Builder();
            request.vertices(list);
            request.createIfNotExist(true);

            Map<String,UpdateStrategy> map = new HashMap<>();
            map.put(UpdateStrategy.APPEND.name(),UpdateStrategy.APPEND);
            request.updatingStrategies(map);
            BatchVertexRequest build = request.build();
            gragh.graph().updateVertices(build);`

报错：
class javax.ws.rs.NotAllowedException: HTTP 405 Method Not Allowed
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:83)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:185)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:167)
	at com.baidu.hugegraph.api.graph.VertexAPI.update(VertexAPI.java:71)
	at com.baidu.hugegraph.driver.GraphManager.updateVertices(GraphManager.java:153)

**Comment by imbajin** [comment]
不好意思, 批量更新的功能文档我会在把loader端代码提交之后补上, 先简单回答一下你的问题:
- 关于更新策略的可选项和使用方式和效果, 可以参考[更新测试类](https://github.com/hugegraph/hugegraph-client/blob/master/src/test/java/com/baidu/hugegraph/api/BatchUpdateElementApiTest.java)
- 简单说`key`就是需要更新的**属性名** (比如`price`), 然后设置对应的策略就行. (`SUM`).

**Comment by wslovenide** [comment]
好的，谢谢回复，今天我把key设置的是属性名，但是执行还是报错，明天试下测试类中的方法

**Comment by wslovenide** [comment]
`
HugeClient hugeClient = new HugeClient(hugeHost,"hugegraph");
        try {
            Vertex vertex = new Vertex("user");
            vertex.id("0");
            vertex.property("active_time",System.currentTimeMillis()); // 有很多属性, 此处只更新一个字段

            BatchVertexRequest.Builder request = new BatchVertexRequest.Builder();
            request.vertices(Lists.newArrayList(vertex))
                   .createIfNotExist(true)
                   .updatingStrategies(ImmutableMap.of("active_time",UpdateStrategy.APPEND));

            hugeClient.graph().updateVertices(request.build());

        }catch (Exception e){
            e.printStackTrace();
        }finally {
            hugeClient.close();
        }
`

**Comment by imbajin** [comment]
`405` 一般说明client和server发送的请求方式就不一致吧. 

估计是你server端代码没有更新(master), 然后你的请求发送到了原本也是`batch`的**批量创建**接口了(那个要求POST方法, 而更新用的PUT)

**补充:** 如果你不希望把代码直接更新到最新, 可以直接`cherry-pick`一下server端批量更新的提交就行了

**Comment by wslovenide** [comment]
我debug跟踪了代码，这个批量更新的方法调用的是 put ， 另外我的hugegraph-server的版本是0.9.2
是这个版本的有问题嘛？ 还是hugegraph-server拉取master的就可以解决这个问题了

**Comment by imbajin** [comment]
是啊, 我的意思是你server的版本里没有对应的PUT方法, 所以Client发一个PUT-batch请求过去是对不上的.
你可以直接拉取master, 不过可能需要重新初始化一下图.  如果是测试就无所谓了

**Comment by wslovenide** [comment]
好的，了解了，谢谢
