### ISSUE TITLE
NPE when executing BatchExample

### ISSUE THREAD

**Issue by HFatBird** [hugegraph/hugegraph-client#70]
I execute the sample file BatchExample.java. When the schema.indexLabel is executed, the following error occurs:
![Exception](https://user-images.githubusercontent.com/16948019/69638389-8bcf1f80-1095-11ea-9fbb-2cf2a93ef510.png)
After Zhang Yi's help, it was found that the reason was that the service was not initialized. And this may be a hidden danger caused NullPointerException. In file **/hugegraph-client/src/main/java/com/baidu/hugegraph/util/TaskCache.java**
![taskcache](https://user-images.githubusercontent.com/16948019/69639075-e452ec80-1096-11ea-9669-e366bb653b38.png)

**Comment by javeme** [comment]
@HFatBird Thanks for your report, and you are welcome to contribute to fix this issue. [how to contribute](https://github.com/hugegraph/hugegraph/blob/master/CONTRIBUTING.md)
