### ISSUE TITLE
顶点id 策略为 automic 时， 无法添加边

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph-client#90]
将 顶点的 id 策略设置为 automic 时， 先批量添加顶点，顶点添加成功，返回 id, id 为long 类型的一串数据 ，然后再添加边，边的源顶点 ，与 目标顶点都是 已经添加过的顶点 ，都带 id , 在添加边时，graph.addEdges(linkedEdge,true); 或单独添加一条边： graph.addEdge(edgeRelation) 都会报错： java.lang.IllegalArgumentException: Invalid vertex id  ，如果 参数为 false,程序 不报错，但添加的顶点没有了边
边的定义如下 ：

             Edge edgeRelation = new Edge(labelName + "_edgeLabel")
                        .property(finalDisplayKeyName, model.getRelationName());

                edgeRelation.sourceId(Long.parseLong(sourceList.get(0).id().toString()));
                edgeRelation.targetId(Long.parseLong(targetList.get(0).id().toString()));
                edgeRelation.sourceLabel(labelName);
                edgeRelation.targetLabel(labelName);
                edgeRelation.source(sourceList.get(0));
                edgeRelation.target(targetList.get(0))

边的 label:

                edgeLabel = schema.edgeLabel(sourceLabelName + "_edgeLabel")
                        .sourceLabel(sourceLabelName)
                        .targetLabel(targetLabelName)
                        .properties(properties)
                        .nullableKeys(nullableProKeys)
                        .enableLabelIndex(true)
                        .frequency(Frequency.SINGLE)
                        .ifNotExist()
                        .create();

 顶点 label: 

                vtlabel = schema.vertexLabel(labelName)
                        .properties(properties)
                        .nullableKeys(nullableProKeys)
                        .useAutomaticId()
                        .ifNotExist()
                        .create();

调试时，这些都有数据。
环境： hugegraph-0.10.4
           hugegraph-client 1.8.5
           hugegraph-common  1.7.3
           os: center 0s 7

**Comment by wisdoms** [comment]
补充：  在以下环境中也有此问题：
hugegraph-0.10.4
hugegraph-client 1.8.9
hugegraph-common 1.7.9
hugegraph-api 0.9.2

**Comment by javeme** [comment]
@wisdoms 请验证下在调用 graph.addEdge(edgeRelation) 之前，是否能提供顶点id查询出顶点，判断下是否已经成功添加顶点。
