### ISSUE TITLE
执行single example报空指针错，两次执行报错的位置不一样

### ISSUE THREAD

**Issue by sqeered** [hugegraph/hugegraph-client#92]
![5154FA22-29FB-491D-957A-C179F4DE2B65](https://user-images.githubusercontent.com/45146931/89095655-969b3a80-d402-11ea-938d-0c1c280652f9.jpeg)
![Uploading 7B73F7DE-2C87-481E-8696-3EBAC56ECB31.jpeg…]()

**Comment by javeme** [comment]
@sqeered 是否能提供一下复现流程？

**Comment by sqeered** [comment]
> @sqeered 是否能提供一下复现流程？

springboot项目中，client版本1.8.0，mysql作为后端存储，把例子程序作为sevice类的一个方法，controller类中调用该方法
