### ISSUE TITLE
hugeGraph-client创建client报错

### ISSUE THREAD

**Issue by py463360578** [hugegraph/hugegraph-client#98]
搭建了0.10.4版本的hugeGraph server后，启动成功，执行：echo `curl -o /dev/null -s -w %{http_code} "http://localhost:9990/graphs/hugegraph/graph/vertices"`，返回200。
但是，将官方文档中的java client样例拷贝到项目中，hugegraph-client的依赖版本为1.8.0，执行后却报错了，错误信息如下：
![image](https://user-images.githubusercontent.com/40166488/92725868-59ca4800-f39f-11ea-9cb8-2b2bd8ccfd3b.png)

**Comment by mizuki-orion** [comment]
我遇到了同样的问题，搭建的maven项目，然后无法通过代码更新顶点和边的属性；通过loarder导入初始数据和关系后，然后添加数据时，无论时单个数据添加还是批量添加都没成功。批量添加时报The label of vertex can't be null，可顶点的所有属性都已赋值。

**Comment by javeme** [comment]
参考：https://github.com/hugegraph/hugegraph-client/issues/58
