### ISSUE TITLE
根据vertexId获取顶点的api，如果不同label的顶点id之间有重复，则获取不到需要的顶点。

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph-client#99]
前提：
1、顶点id采用customstring策略；
2、不同label的顶点id之间可能会有重复；

问题描述：

com.baidu.hugegraph.driver.getVertex(Object vertexId)

这个方案无法获取到所需的顶点，可能需要提供vertexId+vertexLabel的接口方法。

**Comment by javeme** [comment]
@tmljob 自定义customize id策略时，id是图数据库全局可见的，如果不同的label顶点id重复，表现分以下情况：

1. 当打开检查开关时`vertex.check_customized_id_exist=true`，重复的顶点id无法插入，会抛出错误。
2. 当关闭检查开关时`vertex.check_customized_id_exist=false`（默认），重复的顶点id可以插入，会覆盖掉以前其它类型的顶点，需要尽量保证不出现该情况。另外该情况下可能会出现指向非预期类型顶点的非法边，这种邻接点查询会返回undefined类型的顶点。

**Comment by javeme** [comment]
相关问题：https://github.com/hugegraph/hugegraph/issues/1179
